"use client";

import { Footer, Navbar } from "./components";
import "./globals.css";

import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";

export const metadata = {
  title: "Qpay Soulation Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
