import { Footer, Navbar } from "./components";
import "./globals.css";

export const metadata = {
  title: "Qpay Soulation Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
